AfluexSchool/Controllers/AdminReportsController.cs
using AfluexSchool.Filter;
using AfluexSchool.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;

namespace AfluexSchool.Controllers
{
    public class AdminReportsController : AdminBaseController
    {
        // GET: Reports
        #region Fee
        public ActionResult FeeReport(Reports obj)
        {
            #region Set Permission
            Permissions objPermission = new Permissions("Section List");
            if (Session["PK_AdminID"].ToString() == "1")
            { 
                ViewBag.IsDelete = "";
            }
            else
            {
                ViewBag.IsDelete = "none";
            }
            #endregion

            #region ddlSession
            try
            {
                Student objsess = new Student();
                int count = 0;
                List<SelectListItem> ddlSession = new List<SelectListItem>();

                DataSet dssess = objsess.SessionList();
                if (dssess != null && dssess.Tables.Count > 0 && dssess.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in dssess.Tables[0].Rows)
                    {
                        if (count == 0)
                        {
                            ddlSession.Add(new SelectListItem { Text = "--Select Session--", Value = "0" });
                        }
                        ddlSession.Add(new SelectListItem { Text = r["SessionName"].ToString(), Value = r["Pk_SessionId"].ToString() });
                        count = count + 1;
                    }
                }

                ViewBag.ddlSession = ddlSession;
                obj.Session = Session["SessionId"].ToString();
            }
            catch (Exception ex)
            {
                throw ex;
            }

            #endregion

            #region ddlBindClass
            Reports objclass = new Reports();
            int countClass = 0;
            List<SelectListItem> ddlClass = new List<SelectListItem>();
            DataSet dsClass = objclass.BindClass();

            if (dsClass != null && dsClass.Tables.Count > 0 && dsClass.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in dsClass.Tables[0].Rows)
                {
                    if (countClass == 0)
                    {
                        ddlClass.Add(new SelectListItem { Text = "--Select Class--", Value = "0" });
                    }
                    ddlClass.Add(new SelectListItem { Text = r["ClassName"].ToString(), Value = r["PK_ClassID"].ToString() });
                    countClass = countClass + 1;
                }
            }

            ViewBag.ddlClass = ddlClass;
            #endregion
            List<SelectListItem> ddlsection = new List<SelectListItem>();
            ddlsection.Add(new SelectListItem { Text = "--Select Section--", Value = "0" });
            ViewBag.ddlsection = ddlsection;
            return View(obj);
        }
        [HttpPost]
        [ActionName("FeeReport")]
        [OnAction(ButtonName = "GetDeatils")]
        public ActionResult GetFeeReport(Reports obj)
        {
            #region Set Permission
            Permissions objPermission = new Permissions("Section List");
            if (Session["PK_AdminID"].ToString() == "1")
            {
                ViewBag.IsDelete = "";
            }
            else
            {
                ViewBag.IsDelete = "none";
            }
            #endregion
            List<Reports> lst = new List<Reports>();
            try
            {
                obj.Fk_ClassID = (obj.Fk_ClassID) == "0" ? null : obj.Fk_ClassID;
                obj.Fk_SectionID = (obj.Fk_SectionID) == "0" ? null : obj.Fk_SectionID;
                obj.Session = (obj.Session) == "0" ? null : obj.Session;
                DataSet ds = obj.GetFeeReport();
                if (ds != null && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {
                        foreach (DataRow r in ds.Tables[0].Rows)
                        {
                            Reports obj1 = new Reports();
                            obj1.Amount = r["Amount"].ToString();
                            obj1.ReceiptNo = r["ReceiptNo"].ToString();
                            obj1.PaymentDate = r["PaymentDate"].ToString();
                            obj1.PaymentMode = r["PaymentMode"].ToString();
                            obj1.BankDetails = r["BankDetails"].ToString();
                            obj1.BankDetails = r["BankDetails"].ToString();
                            obj1.EncrptNo = Crypto.Encrypt(r["ReceiptNo"].ToString());
                            obj1.ClassName = r["ClassName"].ToString();
                            obj1.SectionName = r["SectionName"].ToString();
                            obj1.StudentName = r["StudentName"].ToString();
                            obj1.LoginId = r["LoginID"].ToString();

                            lst.Add(obj1);
                        }
                        obj.lstfeedata = lst;

                    }
                    else
                    {
                        TempData["FeeReport"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                    }
                }

            }
            catch (Exception ex)
            {
                TempData["Fee"] = ex.Message;
            }
            #region ddlSession
            try
            {
                Student objsess = new Student();
                int count = 0;
                List<SelectListItem> ddlSession = new List<SelectListItem>();
                DataSet dssess = objsess.SessionList();
                if (dssess != null && dssess.Tables.Count > 0 && dssess.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in dssess.Tables[0].Rows)
                    {
                        if (count == 0)
                        {
                            ddlSession.Add(new SelectListItem { Text = "--Select Session--", Value = "0" });
                        }
                        ddlSession.Add(new SelectListItem { Text = r["SessionName"].ToString(), Value = r["Pk_SessionId"].ToString() });
                        count = count + 1;
                    }
                }
                obj.Session = Session["SessionId"].ToString();
                ViewBag.ddlSession = ddlSession;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            #endregion

            #region ddlBindClass
            Reports objclass = new Reports();
            int countClass = 0;
            List<SelectListItem> ddlClass = new List<SelectListItem>();
            DataSet dsClass = objclass.BindClass();

            if (dsClass != null && dsClass.Tables.Count > 0 && dsClass.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in dsClass.Tables[0].Rows)
                {
                    if (countClass == 0)
                    {
                        ddlClass.Add(new SelectListItem { Text = "--Select Class--", Value = "0" });
                    }
                    ddlClass.Add(new SelectListItem { Text = r["ClassName"].ToString(), Value = r["PK_ClassID"].ToString() });
                    countClass = countClass + 1;
                }
            }

            ViewBag.ddlClass = ddlClass;
            #endregion
            List<SelectListItem> ddlsection = new List<SelectListItem>();
            ddlsection.Add(new SelectListItem { Text = "--Select Section--", Value = "0" });
            ViewBag.ddlsection = ddlsection;
            return View(obj);
        }

        public ActionResult PrintFeerecipt(string Id)
        {
            List<Reports> lst = new List<Reports>();
            Reports obj = new Reports();
            if (Session["ReceiptNo"] != null)
            {
                obj.ReceiptNo = Session["ReceiptNo"].ToString();
            }
            else
            {
                obj.ReceiptNo = Id;
            }

            DataSet ds = obj.PrintReceipt();
            if (ds != null && ds.Tables[0].Rows.Count > 0)
            {
                ViewBag.SessionName = ds.Tables[0].Rows[0]["SessionName"].ToString();
                ViewBag.ReceiptNo = ds.Tables[0].Rows[0]["ReceiptNo"].ToString();
                ViewBag.AddedOn = ds.Tables[0].Rows[0]["AddedOn"].ToString();
                ViewBag.RegistrationNo = ds.Tables[0].Rows[0]["RegistrationNo"].ToString();
                ViewBag.StudentName = ds.Tables[0].Rows[0]["StudentName"].ToString();
                ViewBag.ClassSection = ds.Tables[0].Rows[0]["ClassSection"].ToString();
                ViewBag.FatherName = ds.Tables[0].Rows[0]["FatherName"].ToString();
                ViewBag.DateOfBirth = ds.Tables[0].Rows[0]["DateOfBirth"].ToString();
                ViewBag.Address = ds.Tables[0].Rows[0]["Address"].ToString();
                ViewBag.MonthName = ds.Tables[0].Rows[0]["MonthName"].ToString();
                ViewBag.PaymentMode = ds.Tables[0].Rows[0]["PaymentMode"].ToString();
                ViewBag.BankDetails = ds.Tables[0].Rows[0]["BankDetails"].ToString();
                ViewBag.TotalFee = ds.Tables[0].Rows[0]["TotalFee"].ToString();
                ViewBag.LateFee = ds.Tables[0].Rows[0]["LateFee"].ToString();
                ViewBag.ConcessionFee = ds.Tables[0].Rows[0]["ConcessionFee"].ToString();
                ViewBag.Discount = ds.Tables[0].Rows[0]["Discount"].ToString();
                ViewBag.PaidAmount = ds.Tables[0].Rows[0]["PaidAmount"].ToString();
                ViewBag.Balance = ds.Tables[0].Rows[0]["Balance"].ToString();
                ViewBag.PaidAmountInWords = ds.Tables[0].Rows[0]["PaidAmountInWords"].ToString();
                ViewBag.RecieptBy = ds.Tables[0].Rows[0]["RecieptBy"].ToString();
                ViewBag.Arrear = ds.Tables[0].Rows[0]["Arrear"].ToString();

AfluexSchool/Views/AdminReports/AttendanceReport.cshtml
@model AfluexSchool.Models.Student

@{
    ViewBag.Title = "AttendanceReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 
@using (Html.BeginForm("AttendanceReport", "AdminReports", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data",@autocomplete="off" }))
{
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3><b>Attendance Report</b></h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Reports</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Attendance Report</a></li>
                </ol>
            </div>
        </div>
        <div class="card shadow">
            <div class="card-body">
                @*<p style="color:red">
                    @TempData["LeaveList"]
                </p>*@
                <form>
                    <div class="form-row">
                        <div class="form-group  col-md-3">
                            <label>Class</label>
                            @Html.DropDownListFor(m => m.Fk_ClassID, new SelectList(ViewBag.ddlclass, "Value", "Text"), new { @class = "form-control", @onchange = "return OnchangeSection();" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Section</label>
                            @Html.DropDownListFor(m => m.Fk_SectionID, new SelectList(ViewBag.ddlsection, "Value", "Text"), new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>From Date</label>
                            @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", placeholder = "From Date" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>To Date</label>
                            @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", placeholder = "To Date" })
                        </div>
                        <div class="form-group col-md-3">
                            <input type="submit" class="btn btn-info" name="Search" id="btnsearch" value="Search" />
                        </div>
                    </div>
                </form>

                <div class="table-responsive mt-3">
                    <table id="example5" class="display table" style="min-width:845px">
                        <thead>
                            <tr>
                                <th>S.no</th>
                                <th>StudentName</th>
                                <th>ClassName</th>
                                <th>SectionName</th>
                                <th>AttendanceDate</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                if (Model.listStudent != null)
                                {
                                    int i = 1;
                                    foreach (var item in Model.listStudent)
                                    {
                                        <tr>
                                            <td> @i </td>
                                            <td> @item.studentName </td>
                                            <td> @item.ClassName </td>
                                            <td> @item.SectionName </td>
                                            <td> @item.AttendanceDate </td>
                                            <td> @item.Status </td>
                                        </tr>
                                        i++;
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
}


<script src="../../scripts/jquery-1.10.2.min.js"></script>
<script src="../../Scripts/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">


<script>




    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2029'
    });

    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2029'
    });


    function OnchangeSection() {
        //$("#divload").css({ 'display': '' });
        var value = $('#Fk_ClassID').val();
        //var values = $('#SectionName').val();
        //alert(value);
        $.ajax({
            url: "/Student/GetSectionByClass",
            Type: "Get",
            DataType: "JSON",
            data: { Fk_ClassID: value },
            success: function (data) {
                //$("#divload").css({ 'display': 'none' });
                $("#Fk_SectionID").html(""); // clear before appending new list
                $("#Fk_SectionID").empty();
                $("#Fk_SectionID").append(
                      $('<option></option>').val(0).html('Select Section'));
                $.each(data.ddlsection, function (index, Sectioncount) {
                    $("#Fk_SectionID").append(
                          $('<option></option>').val(Sectioncount.Value).html(Sectioncount.Text));

                });

            }
        });

    }


</script>

AfluexSchool/Views/AdminReports/ConcessionReport.cshtml
@model AfluexSchool.Models.Reports

@{
    ViewBag.Title = "ConcessionReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 @using (Html.BeginForm("ConcessionReport", "AdminReports", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
 {
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3><b>Concession Fee Report</b></h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Reports</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Concession Fee Report</a></li>
                </ol>
            </div>
        </div>
        <div class="card shadow">
            <div class="card-body">
                <p style="color:red">
                    @TempData["ConcessionReport"]
                </p>
                <form>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label>Session</label>
                            @Html.DropDownListFor(m => m.SessionName, new SelectList(ViewBag.ddlSession, "Value", "Text"), new { @class = "form-control" })
                        </div>
                        <div class="form-group  col-md-3">
                            <label>Login Id</label>
                            @Html.TextBoxFor(m => m.LoginId, new { @class = "form-control", placeholder = "Login ID" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Fee Type</label>
                            @Html.DropDownListFor(m => m.FeeTypeName, new SelectList(ViewBag.ddlfeetype, "Value", "Text"), new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Month</label>
                            @Html.DropDownListFor(m => m.MonthName, new SelectList(ViewBag.ddlmonth, "Value", "Text"), new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3">
                            <input type="submit" value="Search" name="GetDeatils" id="GetDeatils" class="btn btn-primary" onclick="return favlidate();" />
                        </div>
                    </div>
                </form>

                <div class="table-responsive mt-3">
                    <table id="example5" class="display table" style="min-width:845px">
                        <thead>
                            <tr>
                                <th>S.no</th>
                                <th>Student</th>
                                <th>Class</th>
                                <th>Section</th>
                                <th>Fee Type</th>
                                <th>Month</th>
                                <th>Concession Fee</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                if (Model.lstfeedata != null)
                                {
                                    int i = 1;
                                    foreach (var item in Model.lstfeedata)
                                    {
                                        <tr>
                                            <td>
                                                @i
                                            </td>
                                            <td>@item.StudentName (@item.LoginId)</td>
                                            <td>@item.ClassName</td>
                                            <td>@item.SectionName</td>
                                            <td>
                                                @item.FeeTypeName
                                            </td>
                                            <td>
                                                @item.MonthName
                                            </td>
                                            <td>
                                                @item.ConcessionFee
                                            </td>
                                        </tr>
                                        i++;
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

 }

AfluexSchool/Views/AdminReports/DueReport.cshtml
@model AfluexSchool.Models.Reports

@{
    ViewBag.Title = "DueReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DueReport", "AdminReports", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3><b>Due Report Details</b></h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Reports</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Due Report Details</a></li>
                </ol>
            </div>
        </div>
        <div class="card shadow">
            <div class="card-body">
                @*<p style="color:red">
                    @TempData["LeaveList"]
                </p>*@
                <form>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label>Date<span style="color:red;">*</span></label>
                            @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3">
                            <label class="d-block">&nbsp;</label>
                            <input type="submit" class="btn btn-info" name="btnsearch" id="btnsearch" value="Search" onclick="return validateform();" />
                        </div>
                    </div>
                </form>

                <div class="table-responsive mt-3">
                    <table id="example5" class="display table" style="min-width:845px">
                        <thead>
                            <tr>
                                <th>S.no</th>
                                <th>Student Name</th>
                                <th>Father Name</th>
                                <th>Mobile</th>
                                <th>Class</th>
                                <th>Section</th>
                                <th>Registration Amt</th>
                                <th>Admission Fee</th>
                                <th>Tuition Fee</th>
                                <th>Examination Fee</th>
                                <th>Computer Fee</th>
                                <th>Other Fee</th>
                                <th style="min-width:45px">Total Fee</th>
                                <th style="min-width:45px">Total Paid</th>
                                <th>Balance</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                if (Model.lstfeedata != null)
                                {
                                    int i = 1;
                                    foreach (var item in Model.lstfeedata)
                                    {
                                        <tr>
                                            <td>@i</td>
                                            <td>@item.StudentName</td>
                                            <td>@item.FatherName</td>
                                            <td>@item.Mobile</td>
                                            <td>@item.ClassName</td>
                                            <td>@item.SectionName</td>
                                            <td>@item.RegistrationAmt</td>
                                            <td>@item.AdmissionFee</td>
                                            <td>@item.TuitionFee</td>
                                            <td>@item.ExaminationFee</td>
                                            <td>@item.Computerfee</td>
                                            <td>@item.Otherfee</td>
                                            <td>@item.Totalfee</td>
                                            <td>@item.TotalPaid</td>
                                            <td>@item.Balance</td>
                                        </tr>
                                        i++;
                                    }
                                }
                            }
                        </tbody>
                        <tfoot style="font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif">
                            <tr>
                                <td></td>
                                <td> </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>Total:-</td>
                                <td>@ViewBag.TotalRegistrationAmt</td>
                                <td>@ViewBag.TotalAdmissionFee</td>
                                <td>@ViewBag.TotalTuitionFee</td>
                                <td>@ViewBag.TotalExaminationFee</td>
                                <td>@ViewBag.TotalComputerfee</td>
                                <td>@ViewBag.TotalOtherfee</td>
                                <td>@ViewBag.TotalTotalfee</td>
                                <td>@ViewBag.TotalTotalPaid</td>
                                <td>@ViewBag.Balance</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>

}

<script src="../../scripts/jquery-1.10.2.min.js"></script>
<script src="../../Scripts/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">

<script>

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
        yearRange: '1950:2029'
    });

    function validateform() {
        $(".errortext").removeClass("errortext");
        if ($('#FromDate').val() == '') {
            $("#FromDate").addClass('errortext');
            $('#FromDate').focus();
            return false;
        }

        return true;
    }
</script>

AfluexSchool/Views/AdminReports/EnquiryReport.cshtml
@model AfluexSchool.Models.Reports

@{
    ViewBag.Title = "EnquiryReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("EnquiryReport", "AdminReports", FormMethod.Post, new { @id = "form1", enctype = "multipart/form-data" }))
{
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3><b>Enquiry Report</b></h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Reports</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Enquiry Report</a></li>
                </ol>
            </div>
        </div>
        <div class="card shadow">
            <div class="card-body">
                <p style="color:red">
                    @TempData["EnquiryReport"]
                </p>
                <div class="table-responsive mt-3">
                    <table id="example5" class="display table" style="min-width:845px">
                        <thead>
                            <tr>
                                <th>S.No</th>
                                <th>ParentName</th>
                                <th>StudentName</th>
                                <th>Class Name</th>
                                <th>Previous School</th>
                                <th>Mobile</th>
                                <th>Email</th>
                                <th>Address</th>
                                <th>Enquiry Date</th>
                                <th>Image</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                if (Model.listEnquiry != null)
                                {
                                    int i = 1;
                                    foreach (var item in Model.listEnquiry)
                                    {
                                        <tr>
                                            <td>
                                                @i
                                            </td>
                                            <td>@item.ParentName</td>
                                            <td>
                                                @item.StudentName
                                            </td>
                                            <td>
                                                @item.ClassName
                                            </td>
                                            <td>
                                                @item.PreviousSchool
                                            </td>
                                            <td>
                                                @item.Mobile
                                            </td>
                                            <td>
                                                @item.Email
                                            </td>
                                            <td>
                                                @item.Address
                                            </td>
                                            <td>
                                                @item.AddedOn
                                            </td>
                                            <td>
                                                <img src="@item.Image" id="img" height="100" width="100">
                                            </td>
                                            <td>
                                                <a href="/AdminReports/DeleteEnquiry?Pk_EnquiryId=@item.Pk_EnquiryId" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure want to delete?')">Delete</a>
                                            </td>
                                        </tr>
                                        i++;
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
}