AfluexSchool/Models/Leave.cs
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace AfluexSchool.Models
{
    public class Leave : Common
    {
        public List<Leave> listStudent { get; set; }
        public string StudentName { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Pk_StudentID { get; set; }
        public string Description { get; set; }
        public string PK_StdntLeaveID { get; set; }
        public List<SelectListItem> ddlStatus { get; set; }
        public List<SelectListItem> ddlSection { get; set; }
        public string PK_ClassID { get; set; }
        public string Fk_SectionID { get; set; }
         public string Session { get; set; }
        public DataSet LeaveListParent()
        {
            SqlParameter[] para ={
                                     new SqlParameter("@FK_ParentID",AddedBy),
                                     new SqlParameter("@FK_StudentID",Pk_StudentID),
                                     new SqlParameter("@FromDate",FromDate),
                                     new SqlParameter("@ToDate",ToDate),
                                     new SqlParameter("@Status",Status),
                                     new SqlParameter("@StudentName",StudentName),
                                     new SqlParameter("@Fk_ClassID",PK_ClassID),
                                     new SqlParameter("@Fk_SectionID",Fk_SectionID),
                                       new SqlParameter("@Sessionid",Session),
                               };
            DataSet ds = Connection.ExecuteQuery("StudentLeaveApplicationList", para);
            return ds;

        }

        public DataSet UpdatingStudentLeaveAplcn()
        {
            SqlParameter[] para ={
                                   new SqlParameter("@PK_StdntLeaveID",PK_StdntLeaveID),
                                    new SqlParameter("@Pk_StudentID",Pk_StudentID),
                                     new SqlParameter("@Description",Description),
                                      new SqlParameter("@UpdatedBy",UpdatedBy),
                                      new SqlParameter("@Status",Status),
                                        new SqlParameter("@SessionID",Session),
                               };
            DataSet ds = Connection.ExecuteQuery("UpdateStudentLeaveApplication", para);
            return ds;
        }

        public DataSet GettingStatus()
        {
            SqlParameter[] para ={
                                   new SqlParameter("@Status",Status)
                               };
            DataSet ds = Connection.ExecuteQuery("SearchLeaveStatus", para);
            return ds;
        }

        public DataSet GetSectionByClass()
        {
            SqlParameter[] para ={
                                    new SqlParameter("@Fk_ClassID",PK_ClassID),
                                };
            DataSet ds = Connection.ExecuteQuery("GetSectionByClass", para);
            return ds;
        }

        public DataSet GetSectionList()
        {
            SqlParameter[] para ={
                                   new SqlParameter("@PK_SectionID",Fk_SectionID)
                               };
            DataSet ds = Connection.ExecuteQuery("GetSectionList", para);
            return ds;
        }

    }
}

AfluexSchool/Controllers/MasterController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using AfluexSchool.Models;
using AfluexSchool.Filter;
using System.Data;
using System.IO;

namespace AfluexSchool.Controllers
{
    public class MasterController : AdminBaseController
    {
        // GET: Master

        #region Session
        public ActionResult SessionMaster(string Pk_SessionId)
        {
            #region Set Permission
            Permissions objPermission = new Permissions("Add Session");
            if (!objPermission.IsView)
            {
                return RedirectToAction("NoPermission", "Home");
            }
            else
            {


            }
            #endregion
            Master model = new Master();
            model.Pk_SessionId = Pk_SessionId;
            if (Pk_SessionId != null)
            {
                DataSet ds = model.GettingSession();
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {
                    model.Pk_SessionId = ds.Tables[0].Rows[0]["Pk_SessionId"].ToString();
                    model.SessionName = ds.Tables[0].Rows[0]["SessionName"].ToString();
                }
            }
            return View(model);
        }

        [HttpPost]
        [OnAction(ButtonName = "SaveSession")]
        [ActionName("SessionMaster")]
        public ActionResult SavingSessionMaster(Master model)
        {
            try
            {
                model.AddedBy = Session["Pk_AdminId"].ToString();
                DataSet ds = model.SavingSession();
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {
                        TempData["SavingSessionMaster"] = "Session Saved";
                    }
                    else if (ds.Tables[0].Rows[0]["Msg"].ToString() == "0")
                    {
                        TempData["SavingSessionMaster"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                        return View(model);
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["SavingSessionMaster"] = ex.Message;
                return View(model);
            }
            return RedirectToAction("SessionMaster");
        }

        public ActionResult SessionList(Master model)
        {
            #region Set Permission
            Permissions objPermission = new Permissions("Session List");
            if (!objPermission.IsView)
            {
                return RedirectToAction("NoPermission", "Home");
            }
           
            if (!objPermission.IsDelete)
            {
                ViewBag.IsDelete = "none";
            }
            else
            {
                ViewBag.IsDelete = "";
            }
            #endregion
            List<Master> lst = new List<Master>();

            DataSet ds = model.GettingSession();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                Session["dt"] = ds.Tables[0];
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Master obj = new Master();
                    obj.SessionName = r["SessionName"].ToString();
                    obj.Pk_SessionId = r["Pk_SessionId"].ToString();
                    obj.isDeleted = r["isDeleted"].ToString();
                    lst.Add(obj);
                }
                model.sessionLst = lst;
            }
            return View(model);
        }

        [HttpPost]
        [OnAction(ButtonName = "UpdateSession")]
        [ActionName("SessionMaster")]
        public ActionResult UpdatingSession(Master model)
        {
            try
            {
                model.UpdatedBy = Session["Pk_AdminId"].ToString();
                model.Pk_SessionId = model.Pk_SessionId;
                DataSet ds = model.UpdatingSession();
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {
                        TempData["SessionList"] = "Session Updated";
                    }
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "0")
                    {
                        TempData["SessionList"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                        return View(model);
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["SavingSessionMaster"] = ex.Message;
                return View(model);

            }
            return RedirectToAction("SessionList");
        }

        public ActionResult DeletingSession(string Pk_SessionId)
        {
            Master model = new Master();
            try
            {

                model.DeletedBy = Session["Pk_AdminId"].ToString();
                model.Pk_SessionId = Pk_SessionId;
                DataSet ds = model.DeletingSession();
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {
                        TempData["SessionList"] = "New Session Activated";
                    }
                    else if (ds.Tables[0].Rows[0]["Msg"].ToString() == "0")
                    {
                        TempData["SessionList"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                        return View(model);
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["SessionList"] = ex.Message;
                return View(model);

            }
            return RedirectToAction("SessionList");
        }

        #endregion

        #region Class

        public ActionResult Class(string Pk_ClassId)
        {
            #region Set Permission
            Permissions objPermission = new Permissions("Add Class");
            if (!objPermission.IsView)
            {
                return RedirectToAction("NoPermission","Home");
            }
            else
            {


            }
            #endregion
            Master model = new Master();
            model.Pk_ClassId = Pk_ClassId;
            if (Pk_ClassId != null)
            {
                DataSet ds = model.GettingClass();
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {
                    model.ClassName = ds.Tables[0].Rows[0]["ClassName"].ToString();
                    model.Pk_ClassId = ds.Tables[0].Rows[0]["Pk_ClassId"].ToString();
                }
            }
            return View(model);
        }

        [HttpPost]
        [OnAction(ButtonName = "SaveClass")]
        [ActionName("Class")]
        public ActionResult SavingClass(Master model)
        {
            try
            {
                model.AddedBy = Session["Pk_AdminId"].ToString();
                DataSet ds = model.SavingClass();
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {
                        TempData["Class"] = "Class Saved Successfully";
                    }
                    else if (ds.Tables[0].Rows[0]["Msg"].ToString() == "0")
                    {
                        TempData["Class"] = ds.Tables[0].Rows[0]["ErrorMessage"].ToString();
                        return View(model);
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["Class"] = ex.Message;
                return View(model);
            }

            return RedirectToAction("Class");
        }

        public ActionResult ClassList(Master model)
        {
            #region Set Permission
            Permissions objPermission = new Permissions("Class List");
            if (!objPermission.IsView)
            {
                return RedirectToAction("NoPermission", "Home");
            }
            if (!objPermission.IsUpdate)
            {
                ViewBag.IsEdit = "none";
            }
            else
            {
                ViewBag.IsEdit = "";
            }
            if (!objPermission.IsDelete)
            {
                ViewBag.IsDelete = "none";
            }
            else
            {
                ViewBag.IsDelete = "";
            }
            #endregion
            List<Master> list = new List<Master>();
            DataSet ds = model.GettingClass();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                Session["dt"] = ds.Tables[0];
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    Master obj = new Master();
                    obj.Pk_ClassId = r["PK_ClassID"].ToString();
                    obj.ClassName = r["ClassName"].ToString();
                    list.Add(obj);
                }
                model.classLst = list;
            }
            return View(model);
        }

        [HttpPost]
        [OnAction(ButtonName = "UpdateClass")]
        [ActionName("Class")]
        public ActionResult UpdateClass(Master model)
        {
            try
            {
                model.UpdatedBy = Session["Pk_AdminId"].ToString();
                model.Pk_ClassId = model.Pk_ClassId;
                DataSet ds = model.UpdatingClass();
                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {
                    if (ds.Tables[0].Rows[0]["Msg"].ToString() == "1")
                    {
                        TempData["ClassList"] = "Class Updated Successfully";

AfluexSchool/Views/Master/AssignClassTeacherList.cshtml
@model AfluexSchool.Models.Master

@{
    ViewBag.Title = "AssignClassTeacherList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("AssignClassTeacherList", "Master", FormMethod.Post, new { @id = "AssignClassTeacherList" }))
{
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3><b>Assign Class Teacher List</b></h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Teacher</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Assign Class Teacher List</a></li>
                </ol>
            </div>
        </div>
        <div class="card shadow">
            <div class="card-body">
                <p style="color:red">
                    @TempData["AssignClassTeacherList"]
                </p>
                <form>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label>Teacher</label>
                            @Html.DropDownListFor(m => m.PK_TeacherID, new SelectList(ViewBag.ddlTeacherName, "Value", "Text"), new { @class = "form-control" })
                        </div>
                        <div class="form-group  col-md-3">
                            <label>Class</label>
                            @Html.DropDownListFor(m => m.Pk_ClassId, new SelectList(ViewBag.ddlClassName, "Value", "Text"), new { @class = "form-control", @onchange = "return GetSection()" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Section</label>
                            @Html.DropDownListFor(m => m.PK_SectionId, new SelectList(ViewBag.ddlSectionName, "Value", "Text"), new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3">
                            <label class="d-block">&nbsp;</label>
                            <input type="submit" class="btn btn-info" name="btnsearch" id="btnsearch" value="Search" />
                        </div>
                        
                    </div>
                </form>

                <div class="table-responsive mt-3">
                    <table id="example5" class="display table" style="min-width:845px">
                        <thead>
                            <tr>
                                <th>Sr.No.</th>
                                <th>Teacher Name</th>
                                <th>Class Name</th>
                                <th>Section Name</th>
                                <th style="display:@ViewBag.IsDelete;">Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                if (Model.assignClassTeacherList != null)
                                {
                                    var i = 1;
                                    foreach (var item in Model.assignClassTeacherList)
                                    {
                                        <tr>
                                            <td>@i</td>
                                            <td>@item.Name</td>
                                            <td>@item.ClassName</td>
                                            <td>@item.SectionName</td>
                                            <td style="display:@ViewBag.IsDelete;">
                                                <a href="/Master/DeleteAssignClassTeacher?Pk_AssignClassTeacherId=@item.Pk_AssignClassTeacherId" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure want to delete?')">Delete</a>
                                            </td>
                                        </tr>
                                        i++;
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
}

<script>
    function printData() {

        var divToPrint = document.getElementById("example24");
        newWin = window.open("");
        newWin.document.write(divToPrint.outerHTML);
        newWin.print();
        newWin.close();
    }
    function GetSection() {
        var Pk_ClassId = document.getElementById('Pk_ClassId').value;
        $.ajax({
            url: '/Master/GetSectionByClass',
            data: {
                'Pk_ClassId': $('#Pk_ClassId').val()
            },
            type: 'GET',
            dataType: 'JSON',
            success: function (data) {
                $("#PK_SectionId").html("");
                $("#PK_SectionId").empty();
                $("#PK_SectionId").append(
                      $('<option></option>').val(0).html('--Select Section--'));
                $.each(data.ddlSectionName, function (index, Sectioncount) {
                    $("#PK_SectionId").append(
                          $('<option></option>').val(Sectioncount.Value).html(Sectioncount.Text));
                });
            }
        });
    }
</script>

AfluexSchool/Views/Master/AssignSubjecttoTeacher.cshtml
@model AfluexSchool.Models.Master

@{
    ViewBag.Title = "AssignSubjecttoTeacher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .errortext{
        border:1px solid red!important;
        background-color:#faa9a9!important;
    }
</style>

@using (Html.BeginForm("AssignSubjecttoTeacher", "Master", FormMethod.Post, new { @id = "AssignSubjecttoTeacher" }))
{
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3><b>Assign Subject to Teacher</b></h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Teacher</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Assign Subject to Teacher</a></li>
                </ol>
            </div>
        </div>
        <div class="card shadow">
            <div class="card-body">
                <p style="color:red">
                    @TempData["AssignSubjecttoTeacher"]
                </p>
                <form>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label>Teacher Name<span style="color: red">*</span></label>
                            @Html.DropDownListFor(m => m.PK_TeacherID, new SelectList(ViewBag.ddlTeacherName, "Value", "Text"), new { @class = "form-control", @onchange = "return selectType();" })

                            @Html.HiddenFor(m => m.Pk_SubjecttoTeacherId, new { @class = "form-control" })
                        </div>
                        <div class="form-group  col-md-3">
                            <label>Class Name<span style="color: red">*</span></label>
                            @Html.DropDownListFor(m => m.Pk_ClassId, new SelectList(ViewBag.ddlClassName, "Value", "Text"), new { @class = "form-control", @onchange = "return GetSection()" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Section Name<span style="color: red">*</span></label>
                            @Html.DropDownListFor(m => m.PK_SectionId, new SelectList(ViewBag.ddlSectionName, "Value", "Text"), new { @class = "form-control" })
                        </div>
                        <div class="form-group col-md-3">
                            <label class="d-block">&nbsp;</label>
                            <input type="submit" class="btn btn-success" value="Get Subject" onclick="return getdetails()" name="GetSubjectNameByTeacher" />
                        </div>
                    </div>
                </form>

                <div class="table-responsive mt-3">
                    <table id="example5" class="display table" style="min-width:845px">
                        <thead>
                            <tr>
                                <th>S No.</th>
                                <th>Subject Name</th>
                                <th>Check For Assign</th>
                            </tr>
                        </thead>
                        <tbody id="tblData">
                            @if (Model != null)
                            {
                                if (Model.subjectLst != null)
                                {
                                    int i = 1;
                                    foreach (var item in Model.subjectLst)
                                    {
                                        <tr>
                                            <td>
                                                @i
                                            </td>
                                            <td>
                                                @item.SubjectName
                                            </td>
                                            @if (item.Status == "Checked")
                                            {
                                                <td><input name="chkSelect_ @i" id="chkUnSelect_ @i" type="checkbox" value="Checked" checked /></td>

                                                        <input type="hidden" name="PK_TeacherID_ @i" id="PK_TeacherID_ @i" value="@item.PK_TeacherID" />
                                                        <input type="hidden" name="Pk_ClassId_ @i" id="Pk_ClassId_ @i" value="@item.Pk_ClassId" />
                                                        <input type="hidden" name="PK_SectionId_ @i" id="PK_SectionId_ @i" value="@item.PK_SectionId" />
                                                        <input type="hidden" name="PK_SubjectID_ @i" id="PK_SubjectID_ @i" value="@item.Pk_SubjectId" />
                                                        <input type="hidden" name="SubjectName_ @i" id="SubjectName_ @i" value="@item.SubjectName" />

                                                        <input type="hidden" name="Pk_SubjecttoTeacherId_ @i" id="Pk_SubjecttoTeacherId_ @i" value="@item.Pk_SubjecttoTeacherId" />
                                            }
                                            else
                                            {
                                                <td>
                                                    <input type="checkbox" value="Checked" name="chkSelect_ @i" id="chkUnSelect_ @i" />
                                                    <input type="hidden" name="PK_SubjectID_ @i" id="PK_SubjectID_ @i" value="@item.Pk_SubjectId" />
                                                    <input type="hidden" name="SubjectName_ @i" id="SubjectName_ @i" value="@item.SubjectName" />
                                                    <input type="hidden" name="PK_TeacherID_ @i" id="PK_TeacherID_ @i" value="@item.PK_TeacherID" />
                                                    <input type="hidden" name="Pk_ClassId_ @i" id="Pk_ClassId_ @i" value="@item.Pk_ClassId" />
                                                    <input type="hidden" name="PK_SectionId_ @i" id="PK_SectionId_ @i" value="@item.PK_SectionId" />

                                                    <input type="hidden" name="Pk_SubjecttoTeacherId_ @i" id="Pk_SubjecttoTeacherId_ @i" value="@item.Pk_SubjecttoTeacherId" />
                                                </td>
                                            }
                                        </tr>
                                        i++;
                                    }
                                    <input type="hidden" id="hdRows" name="hdRows" value="@i" />
                                }
                            }
                        </tbody>
                    </table>
                    <div class="col-md-12 mt-3">
                        @if (Model.Pk_SubjecttoTeacherId == null)
                        {
                            <input type="submit" id="btnSave" style="display:none" class="btn btn-success" value="Save" name="btnSave" onclick="return validate();" />

                        }
                        else
                        {
                            <input type="submit" id="btnUpdate" class="btn btn-success" value="Update" name="UpdateSubjectMaster" onclick="return validate();" />

                        }
                    </div>
                </div>

            </div>
        </div>
    </div>

}


<script src="../../AdminPanelcss/assets/js/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
       


        if ($('#PK_TeacherID').val() == 0 && $('#Pk_ClassId').val() == 0 && $('#PK_SectionId').val() == 0) {
            $('#tabl').hide();
            $('#btnSave').hide();
        } else {

            $('#tabl').show();
            $('#btnSave').show();
        }

    });

    function getdetails() {

        $('.errortext').removeClass('errortext');
        $('#divload').css({ 'display': 'none' });

        if ($('#PK_TeacherID').val() == 0) {
            $('#PK_TeacherID').addClass('errortext');
            $('#PK_TeacherID').focus();
            return false;
        }
        if ($('#Pk_ClassId').val() == 0) {
            $('#Pk_ClassId').addClass('errortext');
            $('#Pk_ClassId').focus();
            return false;
        }
        if ($('#PK_SectionId').val() == 0) {
            $('#PK_SectionId').addClass('errortext');
            $('#PK_SectionId').focus();
            return false;
        }
        if ($('#PK_TeacherID').val() == 0 && $('#Pk_ClassId').val() == 0 && $('#PK_SectionId').val() == 0) {
            $('#tabl').hide();
            $('#btnSave').hide();
        } else {

            $('#tabl').show();
            $('#btnSave').show();
        }
    }

    function validate() {

        $('#divload').css({ 'display': 'none' });
        $('.errortext').removeClass('errortext');

        if ($('#PK_TeacherID').val() == 0) {
            $('#PK_TeacherID').addClass('errortext');
            $('#PK_TeacherID').focus();
            return false;
        }
        if ($('#Pk_ClassId').val() == 0) {
            $('#Pk_ClassId').addClass('errortext');
            $('#Pk_ClassId').focus();
            return false;
        }
        if ($('#PK_SectionId').val() == 0) {
            $('#PK_SectionId').addClass('errortext');
            $('#PK_SectionId').focus();
            return false;
        }
    }

    function GetSection() {
        $('#tabl').hide();
        $('#btnSave').hide();
        var Pk_ClassId = document.getElementById('Pk_ClassId').value;
        $.ajax({
            url: '/Master/GetSectionByClass',
            data: {
                'Pk_ClassId': $('#Pk_ClassId').val()
            },
            type: 'GET',
            dataType: 'JSON',
            success: function (data) {
                $("#PK_SectionId").html("");
                $("#PK_SectionId").empty();
                $("#PK_SectionId").append(
                      $('<option></option>').val(0).html('--Select Section--'));
                $.each(data.ddlSectionName, function (index, Sectioncount) {
                    $("#PK_SectionId").append(
                          $('<option></option>').val(Sectioncount.Value).html(Sectioncount.Text));
                });
            }
        });
    }

    function selectType() {
        $('#tabl').hide();
        $('#btnSave').hide();
    }

</script>