AfluexSchool/Models/Leave.cs
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Web.Mvc;

namespace AfluexSchool.Models
{
    public class Leave : Common
    {
        public List<Leave> listStudent { get; set; }
        public string StudentName { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Pk_StudentID { get; set; }
        public string Description { get; set; }
        public string PK_StdntLeaveID { get; set; }
        public List<SelectListItem> ddlStatus { get; set; }
        public List<SelectListItem> ddlSection { get; set; }
        public string PK_ClassID { get; set; }
        public string Fk_SectionID { get; set; }
         public string Session { get; set; }
        public DataSet LeaveListParent()
        {
            SqlParameter[] para ={
                                     new SqlParameter("@FK_ParentID",AddedBy),
                                     new SqlParameter("@FK_StudentID",Pk_StudentID),
                                     new SqlParameter("@FromDate",FromDate),
                                     new SqlParameter("@ToDate",ToDate),
                                     new SqlParameter("@Status",Status),
                                     new SqlParameter("@StudentName",StudentName),
                                     new SqlParameter("@Fk_ClassID",PK_ClassID),
                                     new SqlParameter("@Fk_SectionID",Fk_SectionID),
                                       new SqlParameter("@Sessionid",Session),
                               };
            DataSet ds = Connection.ExecuteQuery("StudentLeaveApplicationList", para);
            return ds;

        }

        public DataSet UpdatingStudentLeaveAplcn()
        {
            SqlParameter[] para ={
                                   new SqlParameter("@PK_StdntLeaveID",PK_StdntLeaveID),
                                    new SqlParameter("@Pk_StudentID",Pk_StudentID),
                                     new SqlParameter("@Description",Description),
                                      new SqlParameter("@UpdatedBy",UpdatedBy),
                                      new SqlParameter("@Status",Status),
                                        new SqlParameter("@SessionID",Session),
                               };
            DataSet ds = Connection.ExecuteQuery("UpdateStudentLeaveApplication", para);
            return ds;
        }

        public DataSet GettingStatus()
        {
            SqlParameter[] para ={
                                   new SqlParameter("@Status",Status)
                               };
            DataSet ds = Connection.ExecuteQuery("SearchLeaveStatus", para);
            return ds;
        }

        public DataSet GetSectionByClass()
        {
            SqlParameter[] para ={
                                    new SqlParameter("@Fk_ClassID",PK_ClassID),
                                };
            DataSet ds = Connection.ExecuteQuery("GetSectionByClass", para);
            return ds;
        }

        public DataSet GetSectionList()
        {
            SqlParameter[] para ={
                                   new SqlParameter("@PK_SectionID",Fk_SectionID)
                               };
            DataSet ds = Connection.ExecuteQuery("GetSectionList", para);
            return ds;
        }

    }
}

AfluexSchool/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AfluexSchool.Models;
using System.Data;
using AfluexSchool.Filter;

namespace AfluexSchool.Controllers
{
    public class LeaveController : AdminBaseController
    {
        // GET: Leave

        #region Approved Declined List

        public ActionResult LeaveList(Leave model)
        {

            #region ddlhelclass+
            try
            {
                Student obj = new Student();
                int count1 = 0;
                List<SelectListItem> ddlClass = new List<SelectListItem>();
                DataSet ds2 = obj.GetClassList();
                if (ds2 != null && ds2.Tables.Count > 0 && ds2.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in ds2.Tables[0].Rows)
                    {
                        if (count1 == 0)
                        {
                            ddlClass.Add(new SelectListItem { Text = "--Select Class--", Value = "0" });
                        }
                        ddlClass.Add(new SelectListItem { Text = r["ClassName"].ToString(), Value = r["PK_ClassID"].ToString() });
                        count1 = count1 + 1;
                    }
                }

                ViewBag.ddlClass = ddlClass;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            #endregion
            List<SelectListItem> ddlSection = new List<SelectListItem>();
            ddlSection.Add(new SelectListItem { Text = "--Select Section--", Value = "0" });
            ViewBag.ddlSection = ddlSection;

            List<SelectListItem> ddlStatus = Common.Status();
            ViewBag.ddlStatus = ddlStatus;

            List<Leave> list = new List<Leave>();
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");
            model.Session = Session["SessionId"].ToString();
            DataSet ds = model.LeaveListParent();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    string s = r["IsApproved"].ToString();
                    if (s != "Pending")
                    {
                        Leave obj = new Leave();

                        obj.Reason = r["Reason"].ToString();
                        obj.FromDate = r["FromDate"].ToString();
                        obj.ToDate = r["ToDate"].ToString();
                        obj.StudentName = r["StudentName"].ToString();
                        obj.Status = r["IsApproved"].ToString();
                        obj.ClassName = r["ClassName"].ToString();
                        obj.SectionName = r["SectionName"].ToString();
                        obj.Pk_StudentID = r["FK_StudentID"].ToString();
                        obj.PK_StdntLeaveID = r["PK_StdntLeaveID"].ToString();
                        obj.Description = r["Description"].ToString();
                        list.Add(obj);
                    }
                }
                model.listStudent = list;
            }
            return View(model);
        }

        [HttpPost]
        [OnAction(ButtonName = "btnSearch")]
        [ActionName("LeaveList")]
        public ActionResult SearchLeave(Leave model)
        {
            List<Leave> list = new List<Leave>();
            if (model.Status == "0") { model.Status = null; }
            if (model.PK_ClassID == "0") { model.PK_ClassID = null; }
            if (model.Fk_SectionID == "0") { model.Fk_SectionID = null; }
            model.FromDate = string.IsNullOrEmpty(model.FromDate) ? null : Common.ConvertToSystemDate(model.FromDate, "dd/MM/yyyy");
            model.ToDate = string.IsNullOrEmpty(model.ToDate) ? null : Common.ConvertToSystemDate(model.ToDate, "dd/MM/yyyy");


            #region ddlhelclass+
            try
            {
                Student obj = new Student();
                int count1 = 0;
                List<SelectListItem> ddlClass = new List<SelectListItem>();
                DataSet ds2 = obj.GetClassList();
                if (ds2 != null && ds2.Tables.Count > 0 && ds2.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in ds2.Tables[0].Rows)
                    {
                        if (count1 == 0)
                        {
                            ddlClass.Add(new SelectListItem { Text = "--Select Class--", Value = "0" });
                        }
                        ddlClass.Add(new SelectListItem { Text = r["ClassName"].ToString(), Value = r["PK_ClassID"].ToString() });
                        count1 = count1 + 1;
                    }
                }

                ViewBag.ddlClass = ddlClass;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            #endregion

            #region ddlsection
            try
            {

                Master obj = new Master();
                obj.Pk_ClassId = model.PK_ClassID;
                if (obj.Pk_ClassId != null)
                {
                    int count4 = 0;
                    List<SelectListItem> ddlSection = new List<SelectListItem>();
                    DataSet ds4 = obj.GettingSectionList();
                    if (ds4 != null && ds4.Tables.Count > 0 && ds4.Tables[0].Rows.Count > 0)
                    {
                        foreach (DataRow r in ds4.Tables[0].Rows)
                        {
                            if (count4 == 0)
                            {
                                ddlSection.Add(new SelectListItem { Text = "--Select Section--", Value = "0" });
                            }
                            ddlSection.Add(new SelectListItem { Text = r["SectionName"].ToString(), Value = r["PK_SectionID"].ToString() });
                            count4 = count4 + 1;
                        }
                    }

                    ViewBag.ddlSection = ddlSection;



                }
                else
                {

                    List<SelectListItem> ddlsection = new List<SelectListItem>();
                    ddlsection.Add(new SelectListItem { Text = "--Select Section--", Value = "0" });
                    ViewBag.ddlSection = ddlsection;
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
            #endregion



            List<SelectListItem> ddlStatus = Common.Status();
            ViewBag.ddlStatus = ddlStatus;
            model.Session = Session["SessionId"].ToString();
            DataSet ds = model.LeaveListParent();
            if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in ds.Tables[0].Rows)
                {
                    string s = r["IsApproved"].ToString();
                    if (s != "Pending")
                    {
                        Leave obj = new Leave();

                        obj.Reason = r["Reason"].ToString();
                        obj.FromDate = r["FromDate"].ToString();
                        obj.ToDate = r["ToDate"].ToString();
                        obj.StudentName = r["StudentName"].ToString();
                        obj.Status = r["isApproved"].ToString();
                        obj.ClassName = r["ClassName"].ToString();
                        obj.SectionName = r["SectionName"].ToString();
                        obj.Pk_StudentID = r["FK_StudentID"].ToString();
                        obj.PK_StdntLeaveID = r["PK_StdntLeaveID"].ToString();
                        obj.Description = r["Description"].ToString();
                        list.Add(obj);
                    }
                }
                model.listStudent = list;
            }


            return View(model);
        }

        public ActionResult GetSectionByClass(string Fk_ClassID)
        {
            Leave model = new Leave();
            try
            {

                model.PK_ClassID = Fk_ClassID;

                List<SelectListItem> ddlSection = new List<SelectListItem>();

                DataSet ds = model.GetSectionByClass();

                if (ds != null && ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
                {


                    foreach (DataRow r in ds.Tables[0].Rows)
                    {

                        ddlSection.Add(new SelectListItem { Text = r["SectionName"].ToString(), Value = r["PK_SectionID"].ToString() });

                    }
                }

                model.ddlSection = ddlSection;

            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Pending Leave

        public ActionResult PendingLeave(Leave model)
        {

            #region Set Permission
            Permissions objPermission = new Permissions("Leave Approval");
            if (!objPermission.IsView)
            {
                return RedirectToAction("NoPermission", "Home");
            }
            if (!objPermission.IsUpdate)
            {
                ViewBag.IsEdit = "none";
            }
            else
            {
                ViewBag.IsEdit = "";
            }
            if (!objPermission.IsDelete)
            {
                ViewBag.IsDelete = "none";
            }
            else
            {
                ViewBag.IsDelete = "";
            }
            #endregion
            // model.PK_TeacherID = Session["PK_TeacherID"].ToString();
            model.Status = "Pending";
            List<Leave> listq = new List<Leave>();
            #region ddlhelclass+
            try
            {

AfluexSchool/Views/Leave/LeaveList.cshtml
@model AfluexSchool.Models.Leave

@{
    ViewBag.Title = "LeaveList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("LeaveList", "Leave", FormMethod.Post, new { @id = "form1" }))
{
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3><b>Leave List</b></h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Leave</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Leave List</a></li>
                </ol>
            </div>
        </div>
        <div class="card shadow">
            <div class="card-body">
                <p style="color:red">
                    @TempData["LeaveList"]
                </p>
                <form>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label>Student</label>
                            @Html.TextBoxFor(m => m.StudentName, new { @class = "form-control", placeholder = "StudentName" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Class</label>
                            @Html.DropDownListFor(m => m.PK_ClassID, new SelectList(ViewBag.ddlClass, "Value", "Text"), new { @class = "form-control", @onchange = "return getSection()" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Section</label>
                            @Html.DropDownListFor(m => m.Fk_SectionID, new SelectList(ViewBag.ddlSection, "Value", "Text"), new { @class = "form-control", })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Status</label>
                            @Html.DropDownListFor(m => m.Status, new SelectList(ViewBag.ddlStatus, "Value", "Text"), new { @class = "form-control", placeholder = "To Date", @ReadOnly = "ReadOnly" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>From Date</label>
                            @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", placeholder = "From Date" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>To Date</label>
                            @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", placeholder = "To Date" })
                        </div>
                        <div class="form-group col-md-3">
                            <label class="d-block">&nbsp;</label>
                            <input type="submit" value="Search" name="btnSearch" id="btnSearch" class="btn btn-primary" />
                        </div>
                    </div>
                </form>

                        <div class="table-responsive mt-3">
                            <table id="example5" class="display table" style="min-width:845px">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Student</th>
                                        <th>From Date</th>
                                        <th>To Date</th>
                                        <th>Reason</th>
                                        <th>Description</th>
                                        <th>Status </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null)
                                    {
                                        if (Model.listStudent != null)
                                        {
                                            int i = 1;
                                            foreach (var item in Model.listStudent)
                                            {
                                                <tr>
                                                    <td>
                                                        @i
                                                    </td>
                                                    <td>@item.StudentName (@item.ClassName - @item.SectionName)</td>
                                                    <td>
                                                        @item.FromDate
                                                    </td>
                                                    <td>
                                                        @item.ToDate
                                                    </td>
                                                    <td>
                                                        @item.Reason
                                                    </td>
                                                    <td>
                                                        @item.Description
                                                    </td>
                                                    <td>
                                                        @item.Status
                                                    </td>

                                                </tr>
                                                i++;
                                            }
                                            <input type="hidden" id="hdRows" name="hdRows" value="@i" />
                                        }
                                    }
                                </tbody>
                            </table>
                            
                        </div>

            </div>
        </div>
    </div>

}

<script src="../../scripts/jquery-1.10.2.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment-with-locales.min.js"></script>


<script>
    $(document).ready(function () {
        $("#divload").css({ 'display': 'none' });
    });

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
    });

    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
    }
);

    function setdescription(evt) {
        $('#Description_').val(evt.value);
        $('#PK_StdntLeaveID_').val();
    }

    function approve(evt) {
        var Description = $('#Description_').val();
        var Pk_StudentID = $('#Pk_StudentID_').val();
        var PK_StdntLeaveID = $('#PK_StdntLeaveID_').val();
        var Approve = $('#Approve').val();

    }
    function decline(evt) {
        var Description = $('#Description_').val();
        var Pk_StudentID = $('#Pk_StudentID_').val();
        var PK_StdntLeaveID = $('#PK_StdntLeaveID_').val();
        var Decline = $('#Decline').val();
    }

    function getSection() {
        var value = $('#PK_ClassID').val();
        $.ajax({
            url: "/Leave/GetSectionByClass",
            Type: "Get",
            DataType: "JSON",
            data: { Fk_ClassID: value },
            success: function (data) {
                $("#Fk_SectionID").html(""); 
                $("#Fk_SectionID").empty();
                $("#Fk_SectionID").append(
                      $('<option></option>').val(0).html('Select Section'));
                $.each(data.ddlSection, function (index, Sectioncount) {
                    $("#Fk_SectionID").append(
                          $('<option></option>').val(Sectioncount.Value).html(Sectioncount.Text));

                });

            }
        });

    }
</script>

AfluexSchool/Views/Leave/PendingLeave.cshtml
@model AfluexSchool.Models.Leave

@{
    ViewBag.Title = "PendingLeave";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("PendingLeave", "Leave", FormMethod.Post, new { @id = "PendingLeave12",@autocomplete="off" }))
{
    <div class="container-fluid">
        <div class="row page-titles mx-0">
            <div class="col-sm-6 p-md-0">
                <div class="welcome-text">
                    <h3><b>Leave Approval</b></h3>
                </div>
            </div>
            <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Leave</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Leave Approval</a></li>
                </ol>
            </div>
        </div>
        <div class="card shadow">
            <p style="color:red">
                @TempData["PendingLeave"]
            </p>
            <div class="card-body">
                <form>
                    <div class="form-row">
                        <div class="form-group col-md-3">
                            <label>Student</label>
                            @Html.TextBoxFor(m => m.StudentName, new { @class = "form-control", placeholder = "StudentName" })
                        </div>
                        <div class="form-group  col-md-3">
                            <label>Class</label>
                            @Html.DropDownListFor(m => m.PK_ClassID, new SelectList(ViewBag.ddlClass, "Value", "Text"), new { @class = "form-control", @onchange = "return getSection()" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>Section</label>
                            @Html.DropDownListFor(m => m.Fk_SectionID, new SelectList(ViewBag.ddlSection, "Value", "Text"), new { @class = "form-control", })
                        </div>
                        <div class="form-group col-md-3">
                            <label>From Date</label>
                            @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", placeholder = "From Date" })
                        </div>
                        <div class="form-group col-md-3">
                            <label>To Date</label>
                            @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", placeholder = "To Date" })
                        </div>
                        <div class="form-group col-md-3">
                            <label class="d-block">&nbsp;</label>
                            <input type="submit" value="Search" name="btnSearch12" id="btnSearch" class="btn btn-primary" />
                        </div>
                    </div>
                </form>

                @if (Model != null)
                {
                    if (Model.listStudent != null)
                    {
                        int i = 1;
                        <div class="table-responsive mt-3">
                            <table id="example5" class="display table" style="min-width:845px">
                                <thead>
                                    <tr>
                                        <th>S.no</th>
                                        <th>Student</th>
                                        <th>From Date    </th>
                                        <th>To Date   </th>
                                        <th>Reason</th>
                                        <th>Description</th>
                                        <th>Status </th>
                                        <th>App/Dec</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.listStudent)
                                    {
                                        <tr>
                                            <td>
                                                @i
                                            </td>
                                            <td>@item.StudentName (@item.ClassName - @item.SectionName)</td>
                                            <td>
                                                @item.FromDate
                                            </td>
                                            <td>
                                                @item.ToDate
                                            </td>
                                            <td>
                                                @item.Reason
                                            </td>
                                            @if (item.Status == "Pending")
                                            {
                                                <td>
                                                    <input type="text" name="Description_ @i" id="Description_" value="@item.Description" onchange="return setdescription(this)" />
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    <input type="text" name="Description_ @i" id="Description_" value="@item.Description" readonly="readonly" />
                                                </td>
                                            }
                                            <td>
                                                @item.Status
                                            </td>
                                            @if (item.Status == "Pending")
                                            {
                                                <td>
                                                    <input name="chkSelect_ @i" id="chkUnSelect_ @i" type="checkbox" value="Checked" />
                                                    <input type="hidden" name="Pk_StudentID_ @i" id="Pk_StudentID_ @i" value="@item.Pk_StudentID" />
                                                    <input type="hidden" name="Description_ @i" id="Description_ @i" value="@item.Description" />
                                                    <input type="hidden" name="PK_StdntLeaveID_ @i" id="PK_StdntLeaveID_" value="@item.PK_StdntLeaveID" />
                                                </td>
                                            }
                                            else
                                            {
                                                <td>
                                                    <input name="chkSelect_ @i" id="chkUnSelect_ @i" type="checkbox" onclick="return false" checked />
                                                </td>
                                            }
                                        </tr>
                                        i++;
                                    }
                                    <input type="hidden" id="hdRows" name="hdRows" value="@i" />

                                </tbody>
                            </table>
                                <div class="col-md-12 mt-3 mb-3">
                                    <input style="display:@ViewBag.IsEdit;" type="submit" name="ApproveLeave" id="Approve" value="Approve" class="btn btn-success btn-sm" onclick="return approve(this)">
                                    <input style="display:@ViewBag.IsDelete;" type="submit" name="DeclineLeave" id="Decline" value="Decline" class="btn btn-danger btn-sm" onclick="return decline(this)" />
                                </div>
                        </div>
                    }
                }

            </div>
        </div>
    </div>
    
}

<script src="../../scripts/jquery-1.10.2.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment-with-locales.min.js"></script>


<script>
    $(document).ready(function () {
        $("#divload").css({ 'display': 'none' });
    });

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
    });

    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeMonth: true,
        changeYear: true,
    }
);

    function setdescription(evt) {
        $('#Description_').val(evt.value);
        $('#PK_StdntLeaveID_').val();
    }

    function approve(evt) {
        var Description = $('#Description_').val();
        var Pk_StudentID = $('#Pk_StudentID_').val();
        var PK_StdntLeaveID = $('#PK_StdntLeaveID_').val();
        var Approve = $('#Approve').val();

    }
    function decline(evt) {
        var Description = $('#Description_').val();
        var Pk_StudentID = $('#Pk_StudentID_').val();
        var PK_StdntLeaveID = $('#PK_StdntLeaveID_').val();
        var Decline = $('#Decline').val();
    }

    function getSection() {
        var value = $('#PK_ClassID').val();
        $.ajax({
            url: "/TeacherLogin/GetSecByCla",
            Type: "Get",
            DataType: "JSON",
            data: { Fk_ClassID: value },
            success: function (data) {
                $("#Fk_SectionID").html("");
                $("#Fk_SectionID").empty();
                $("#Fk_SectionID").append(
                      $('<option></option>').val(0).html('Select Section'));
                $.each(data.ddlSection, function (index, Sectioncount) {
                    $("#Fk_SectionID").append(
                          $('<option></option>').val(Sectioncount.Value).html(Sectioncount.Text));

                });

            }
        });

    }
</script>